### ISSUE TITLE
Request re-loading and propose form clearing

### ISSUE THREAD

**Issue by joelhooks** [eggheadio/egghead-instructor-center#149]
This first one looks like the technologies are getting called on any input change. Not really a big deal but should probably be throttled. Technologies don't change much.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0I3d0H1c1G1X3s0v1E1J/Screen%20Recording%202017-03-07%20at%2002.28%20PM.gif?v=a7566d7f)

The server could definitely send back a better error here, but maybe if we just min-length to 5-10 it will stop. It is 5 on the server, but even that is super short.

Right now on error it clears the form and doesn't allow us to re-submit!

![](https://d3vv6lp55qjaqc.cloudfront.net/items/0U0O0J2U2Y071v0V2g17/Screen%20Recording%202017-03-07%20at%2002.29%20PM.gif?v=87b184c5)

**Comment by trevordmiller** [comment]
Good catch. I've moved it to my board.

**Comment by trevordmiller** [comment]
This is also a problem on screen switching; the navigation disappears and you have the root loading spinner so the app doesn't feel like a SPA; I need to figure out why Request is making more requests. My guess is I need a shouldComponentUpdate or something. This is at the top of my ready column.

**Comment by trevordmiller** [comment]
I fixed the navigation re-routing issue by moving the `WrappedRequest` below it; but this is still annoying; will most likely look into it tomorrow after my current PR.

**Comment by trevordmiller** [comment]
Will be fixed by https://github.com/eggheadio/egghead-instructor-center/pull/163#pullrequestreview-26436843
