### ISSUE TITLE
Simplify environments

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#152]
I'd like to remove `.env` entirely with a simpler approach.

## Implementation

- [x] `yarn dev` uses local dev , `yarn dev:staging`, `yarn dev:prod` or .env_template
- [x] Update README

**Comment by joelhooks** [comment]
Can we switch local to plain dev and staging to dev:staging please? I understand it won't "just work" for the very occasional lookie lou and even rarer contributor. That seems fine though.

**Comment by trevordmiller** [comment]
Sounds good. I can also do the .env_template thing if for some reason yarn scripts doesn't work.
