### ISSUE TITLE
Add direct video uploader

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#168]
Would be good to replace the `Upload video` button with an inline uploader.

More info:
https://github.com/eggheadio/egghead-rails/pull/1210/files#diff-ca9e323ab2d1da4afd04d7dc125d35d6

**Comment by joelhooks** [comment]
I don't think this is needed right now. We will move a discussion about the ux of the lesson creation process a priority, but I want to wait until after we get the primary lesson screen updated.

Really, the lesson screen is the fundamental atom of this entire business, and should probably have its own project.

**Comment by trevordmiller** [comment]
@joelhooks 

> " I want to wait until after we get the primary lesson screen updated"

I created this story to replace the "Upload/Replace Video" button with a direct upload/replace on the individual lesson screen (`https://instructor.egghead.io/lessons/{lessonSlug}`), so it doesn't need to link to the old page. I feel that is an improvement to the lesson screen.

Or are you talking about deleting the Instructor Center lesson screen and moving back to the old lesson screen? I'm a bit confused.

**Comment by joelhooks** [comment]
> Or are you talking about deleting the Instructor Center lesson screen and moving back to the old lesson screen?

This is what will be occurring, yes. We will have a single full featured lesson page that lives at https://egghead.io/lessons/lesson-slug

**Comment by trevordmiller** [comment]
> "This is what will be occurring, yes. We will have a single full featured lesson page that lives at https://egghead.io/lessons/lesson-slug"

Good to know. Could you explain this to me a bit more so I understand the reasoning and expectations for the future? This is a shift in the direction I have been working towards - I thought I was going to continue to build out the instructor-specific components and screens in the Instructor Center and then export the app to render in egghead-rails per https://github.com/eggheadio/egghead-instructor-center/issues/186. What other functionality are you planning to remove from the instructor center and put back in egghead-rails? What will the purpose of the Instructor Center repo be if a lot of functionality is moving back directly into egghead-rails, and who will build it?

**Comment by joelhooks** [comment]
> I thought I was going to continue to build out the instructor-specific components and screens in the Instructor Center and then export the app to render in egghead-rails per #186

This is the plan. We aren't going to build two independent lesson pages (or course pages). 

Here's some design details: https://egghead.invisionapp.com/d/main#/console/10399246/224995160/preview

We've got definite set of components that are instructor specific. Viewing a lesson isn't one of them.

Here's some initial discussion of the data and behaviors required to create a lesson. It is ready for @vojtaholik to add to his design rotation IMO https://paper.dropbox.com/doc/04.-Creating-and-Editing-Lessons-F5dtd2f1WXKyOnyGOZsrK

**Comment by trevordmiller** [comment]
Ok, I'm closing this issue then and created this:
https://github.com/eggheadio/egghead-instructor-center/issues/203
