### ISSUE TITLE
Move lesson proposal into requested card component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#174]
The requested lessons card should be updated with a new "Propose a new topic" link at the top of the list which takes the instructor to the `/new` route (which includes lesson proposal). Then the lesson proposal card on the dashboard screen.

![image](https://cloud.githubusercontent.com/assets/5497885/24370844/151c5e48-12e6-11e7-85b5-ea75d5224c67.png)

Mock source:
https://egghead.invisionapp.com/share/KQB170ZD6#/screens

**Comment by joelhooks** [comment]
@vojtaholik @trevordmiller the list of requested lessons doesn't suggest to me at all that I can claim one. Feels like it needs to let me know that somehow, aside from the explainer text (which could probably be removed if we had appropriate UI affordance)

**Comment by trevordmiller** [comment]
Agreed. @vojtaholik, I already have a `LessonList` comonent that wilI be upgraded (https://github.com/eggheadio/egghead-instructor-center/issues/176) which currently includes available lesson actions:

![image](https://cloud.githubusercontent.com/assets/5497885/24325558/efc54938-1160-11e7-84c5-d35ce4fb8dea.png)

Once this component ^ is polished in https://github.com/eggheadio/egghead-instructor-center/issues/176 with the new styles, the "Requested Topics" seems to be a condensed version of the full Lesson List component. But per Joel's comment here, it seems it needs to keep the available lesson actions (which will be just `Claim` for most or `Cancel` for admins / the creator of the lesson).

**Comment by trevordmiller** [comment]
Moving this back to the "Discussion" column.

**Comment by trevordmiller** [comment]
Moving discussion of the "condensed" version of the lesson list showing actions to https://github.com/eggheadio/egghead-instructor-center/issues/176 as that is where it will be worked on. This issue is just to replace the "Propose" card component on the dashboard screen with a link at the top of the requested lessons card component.
![image](https://cloud.githubusercontent.com/assets/5497885/24325804/a98fffde-1166-11e7-85b2-19ffb7dd74d4.png)

**Comment by vojtaholik** [comment]
> the list of requested lessons doesn't suggest to me at all that I can claim one.

Agree, updated ⚙️   https://egghead.invisionapp.com/share/KQB170ZD6
All other pages with requested topics component updated as well.

**Comment by trevordmiller** [comment]
Thanks @vojtaholik, I updated https://github.com/eggheadio/egghead-instructor-center/issues/176 to match.

**Comment by joelhooks** [comment]
will this expand in place with a the form?

**Comment by vojtaholik** [comment]
@joelhooks very nice! It sure can. I have a sketch of this principle for the requested topics ⚙️  from earlier http://cloud.egghead.io/0m1m0K010o0G

**Comment by trevordmiller** [comment]
> "will this expand in place with a the form?"

The issue currently says "The requested lessons card should be updated with a new "Propose a new topic" link at the top of the list which takes the instructor to the /new route (which includes lesson proposal)"

Referring to linking to this screen: https://instructor.egghead.io/lessons/new

But we could expand to show the form inline if that would be a better experience. I'm happy with it either way so will defer to @vojtaholik on that.

**Comment by trevordmiller** [comment]
> "@joelhooks very nice! It sure can. I have a sketch of this principle for the requested topics ⚙️ from earlier http://cloud.egghead.io/0m1m0K010o0G"

Great idea Vojta; this would need to be designed in a way to work with switching from "technology" to "tags" though; not sure if there will be too many tags available to have them be tappable icons - might be better to have an auto-filled form? Or maybe if the list of icons can be filtered - like how an emoji selection list works:

![image](https://cloud.githubusercontent.com/assets/5497885/24372085/0a68688a-12ea-11e7-830e-27c9a9cfe381.png)

**Comment by joelhooks** [comment]
you could show a limited set of popular tags, but tagging is going to be super tricky. Basically everything is JavaScript, so it ends up with 1400 lessons and is useless as a taxonomy element.

It's a bit of a UX rubic's cube.

**Comment by vojtaholik** [comment]
yes @trevordmiller, it would need some more work for sure. 👍 

I love the idea of having more content in one card in general. Basically avoid nesting :) Can we do that? And can we have steps and so in it? This kind of "mobile" approach rules.

**Comment by trevordmiller** [comment]
Ok, I'd suggest we keep this story contained to just moving the current "Propose Lesson" form inside the "Requested Lessons", hidden by default with the new "+" option which expands to show it (yes I can do that easily Vojta); then tags and polishing the lesson proposal step process can be another story once Vojta has time to tinker with it. Does that sound reasonable?

**Comment by vojtaholik** [comment]
Sounds good Trevor, good work on this so far, thanks!

**Comment by trevordmiller** [comment]
Thanks @vojtaholik; I'm happy to update what has been built with a more granular and pretty treatment once the "+ PROPOSE NEW TOPIC" has been toggled. If you end up designing it, let's make another story and discuss :)
