### ISSUE TITLE
Polish icon component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#178]
New icon options need to be added: question mark, edit pencil, upload, info without circle, plus, check without circle, horizontal three dots. We already have the "X", right chevron, and check in circle options.

![image](https://cloud.githubusercontent.com/assets/5497885/24315480/d979d0d6-10ac-11e7-92aa-93cb20b2e62a.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24315486/e73e6c0e-10ac-11e7-81c7-6b1ad0b585e1.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24315495/f82f8688-10ac-11e7-8b9b-1f29fbb336f2.png)

## Implementation notes

- [x] Fork react-icons (https://github.com/gorangajic/react-icons)
- [x] In the forked react-icons add a new `egghead` directory and set it up like the `fa` one with the  custom SVGs attached to this story
- [x] Change the `egghead-ui` react-icons to use the fork here https://github.com/eggheadio/egghead-ui/blob/master/package.json#L46
- [x] Add the custom icon types to the egghead-ui `Icon` component here: https://github.com/eggheadio/egghead-ui/blob/master/src/components/Icon/index.js#L3-L63;  don't remove any FA types as they are all currently in use; just extend what is there with the custom `egghead*` types
- [x] Ensure styleguide at localhost:2000 is still good
- [x] Let egghead-rails team know about this PR so they can add their `Icon` types + svgs from https://github.com/eggheadio/egghead-rails/tree/1d13569b875407c60354d3e508d2d42ef862a864/client/app/components/icons
- [x] Use the new icon types in egghead-instructor-center once https://github.com/eggheadio/egghead-ui/pull/104 is merged

**Comment by vojtaholik** [comment]
SVGs:
[icons.zip](https://github.com/eggheadio/egghead-instructor-center/files/872691/icons.zip)

**Comment by trevordmiller** [comment]
@vojtaholik Thanks for the icons Vojta. Do you feel these belong in "egghead-ui" or do you plan to only use them in the instructor center? I could extend the font awesome SVGs currently in `egghead-ui` with custom SVGs.

**Comment by vojtaholik** [comment]
@trevordmiller actually I think @justin808 have already set some of them up for list ⚙️ component. I think all icons should at some point end up in egghead-ui, like a basic, character level component used all across other ⚙️ s :)  

Let's have our own egghead _fontawesome_ icon set:)

**Comment by trevordmiller** [comment]
@vojtaholik Ok sounds good. This is what we have now: https://github.com/eggheadio/egghead-ui/blob/master/src/components/Icon/index.js

With the examples for ^ rendered here:
http://styleguide.egghead.io/?selectedKind=Icon&selectedStory=Info&full=0&down=1&left=1&panelRight=0
http://styleguide.egghead.io/?selectedKind=Icon&selectedStory=Combinations&full=0&down=1&left=1&panelRight=0

With this story I can extend the egghead-ui `Icon` component to have the custom SVGs you uploaded.

**Comment by joelhooks** [comment]
https://github.com/eggheadio/egghead-rails/tree/1d13569b875407c60354d3e508d2d42ef862a864/client/app/components/icons

Here's the existing work in code for the icons.

**Comment by trevordmiller** [comment]
@joelhooks So it sounds like for this story, if I update the egghead-ui `Icon` component with the new SVGs Vojta added to this issue as well as the SVGs in the egghead-rails directory you linked, then each project could just use `Icon` from `egghead-rails`; does that sound like a good plan?

**Comment by justin808** [comment]
@trevordmiller Are you going to dynamically use the code from egghead-rails, or duplicate the files?

**Comment by trevordmiller** [comment]
@justin808 Off the top of my head the best approach would be to fork [`react-icons`](https://github.com/gorangajic/react-icons) and add a new SVG folder and then consume it as we are doing in egghead-ui:
https://github.com/eggheadio/egghead-ui/blob/master/src/components/Icon/index.js

And consume the `Icon` component from egghead-ui like we already do, just with new `type` options:
https://github.com/eggheadio/egghead-instructor-center/blob/master/src/components/Anchor/index.js#L15-L18

Which renders like this:
![image](https://cloud.githubusercontent.com/assets/5497885/24379864/3f6cc0b4-1306-11e7-944b-63525e6f93b2.png)

See the egghead-ui examples and documentation of this currently:
http://styleguide.egghead.io/?selectedKind=Icon&selectedStory=Info&full=0&down=1&left=1&panelRight=0

This would allow us to continue to use other icon libraries, with our own SVGs, from one source - without requiring all the image files be in the projects directly.

**Comment by justin808** [comment]
@trevordmiller that's a slick idea! 

So just like this: https://github.com/gorangajic/react-icons/blob/master/fa/align-center.js

But have the directory be `egghead` rather than `fa` and replace the SVGs.

**Comment by trevordmiller** [comment]
@justin808 Yes. Thanks :)

**Comment by trevordmiller** [comment]
That would be my suggestion anyways. Not sure if everyone likes that or not. It would be easy to implement since we already have react-icons wired up with `Icon` in egghead-ui; so it would be a non-breaking upgrade (just adding `type` options).

**Comment by joelhooks** [comment]
I really like the idea of having fa to fall back on, but working towards building a bespoke icon set. The "easy way" sounds great.

**Comment by trevordmiller** [comment]
Ok cool, moving this to the "Ready to implement" column. If someone wants to grab it, go for it. I'm happy to help too just let me know. If not, I'll get to it.

**Comment by trevordmiller** [comment]
Relies on https://github.com/eggheadio/egghead-ui/pull/104
