### ISSUE TITLE
Sort lesson pages by state and release order

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#179]
Currently we're using calls like `/api/v1/lessons?page=1&size=10&state=proposed,accepted,requested,claimed,submitted,rejected,updated` which splits up pages with mixed states (so for example, `Claimed` lessons could be on both page one and three with other states between). We're sorting by state on the client, but unless this is also done on the server, the pages are a bit confusing.

We could also add a note if a lesson is a part of a course that it is waiting for the entire course to be released or filter it out?

**Comment by trevordmiller** [comment]
The back-end now supports this so I moved it to "Ready to implement" for the front end.
https://github.com/eggheadio/egghead-rails/pull/1219
We should be able to now use this `sort_by` param in the `PaginatedLessonList` component request.

**Comment by trevordmiller** [comment]
I think I've found a bug in the endpoints that has been broken for a bit, but I just noticed it when trying to implement `sort_by`:
![image](https://cloud.githubusercontent.com/assets/5497885/24172335/7686e1a0-0e4d-11e7-838d-24c9164ffb64.png)

Can reproduce in dev and staging. Working with Pete to figure it out.

**Comment by trevordmiller** [comment]
stashed changes in `sort-lessons` branch

**Comment by trevordmiller** [comment]
Waiting for [Pete's PR to be merged](https://github.com/eggheadio/egghead-rails/pull/1245); after, I can update from `size` to `per_page` to fix the link header and then use the new `?without_course=true` param on `In Queue` so it only shows the ~20 stand-alone lessons in `row_order` instead of 179 including (those in courses). Ideally in the future it would be cool to have the course itself be listed like a stand-alone lesson in `In Review` / `In Queue` so that lesson lists become "item lists" that show top level / entry point items (stand-alone lessons or courses, without lesson instead courses) like what is in "The Knowledge Firehose" section of https://egghead.io/lessons.

**Comment by joelhooks** [comment]
>  Ideally in the future it would be cool to have the course itself be listed like a stand-alone lesson in In Review / In Queue so that lesson lists become "item lists" that show top level / entry point items (stand-alone lessons or courses, without lesson instead courses) like what is in "The Knowledge Firehose" section of https://egghead.io/lessons

If we are talking about un-published content you can just do this client side because you won't hit the tipping point of sad slowness since the lesson counts will be realtively small and you don't need to paginate. I personally would rather not have a paginated pre-publish list because I want to see the whole body of work without clicking through pages.

The firehose page is a weird [crappy stack of hack ruby code](https://github.com/eggheadio/egghead-rails/blob/master/app/controllers/lessons_controller.rb#L360-L375) and there's no api for general content yet.

**Comment by trevordmiller** [comment]
@joelhooks I think showing all lessons on the "In progress" and "In review" tabs would be good (since each lesson can be worked on and reviewed individually usually regardless of if it is in a course or not); but for "In queue" and "Published", in the future I'd like to boil it down to just stand-alone lessons and courses like the "Knowlege Firehose" on egghead.io works; right now because we have so many courses in the works, we have ~150 lessons in "In Queue" (approved lessons) which does need pagination (currently 20 per page so there are 7+ pages); for this issue, I'll add the `without_courses` to "In Queue" and "Published" so that they only show stand-alone lessons and then we can re-evaluate courses separately in the future; not quite ready to discuss it but it is in the "Discuss" column on the IC board.

**Comment by joelhooks** [comment]
> we can re-evaluate courses separately in the future; not quite ready to discuss it

OK, I won't spoil the ending then ;)
