### ISSUE TITLE
Remove extra info from lesson groups

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#183]
"Published" can be removed from the dashboard lesson groups; it will remain on the "Lessons" lesson groups though.

![image](https://cloud.githubusercontent.com/assets/5497885/24111202/55e5e632-0d5b-11e7-821b-e08c86c241b1.png)

The help text can be removed from "In progress" and "Published"

![image](https://cloud.githubusercontent.com/assets/5497885/24111341/c2b805c4-0d5b-11e7-8d0c-9bfa15134fea.png)

**Comment by vojtaholik** [comment]
![1](https://cloud.githubusercontent.com/assets/25487857/24112354/8c1c51e4-0d99-11e7-9f7d-6956c3deb1e6.png)
I think you're right @trevordmiller and best way to show this info is variant A as you proposed. ;)
