### ISSUE TITLE
Move rendering into egghead-rails

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#186]
We are planning to move the Instructor Center rendering into egghead-rails so that the `/instructor` egghead-rails route renders the app (all screens). This is to improve the user experience of having a single app feel.

More information and discussion:
https://paper.dropbox.com/doc/egghead-project-boundaries-NxDI1mVZz1fr0ep3ecLax

**Comment by trevordmiller** [comment]
An idea for implementation of this:
We could just wrap the `src/index.js` in an exported `App` component, then `src/index.js` can export `App`; then we could publish the entire app as a package on npm for importing and rendering into an `egghead-rails` route like we do with `egghead-ui` components. The only issue I see with this is the relative routes like `/instructors` and `/` would need to be prefixed with an environment variable. But the benefit of this is that the instructor center can still be developed and rendered on it's own but can also be rendered by another project. @joelhooks does this sound like a reasonable plan?

**Comment by joelhooks** [comment]
Yes, that sounds fine to me. We will also want to be able to peel off screens independently. On the rails side, we can pass a "base route" property.

I think it would actually be really cool to make this the `/instructors` route and move their profile display and management over to this project. Would that be a reasonable goal?

**Comment by trevordmiller** [comment]
Sounds good to me. I'll leave this here in the "Discussion" column for now until I finish up the polishing stories for the new mocks, but then we can jump back to this.

**Comment by trevordmiller** [comment]
Joel and I just had a discussion over the phone and decided that the next steps for this will be to publish the instructor center screens so they can be imported and rendered inside the egghead-rails routing system. We will most likely need some sort of screen API to deal with passing route-based props. I'll start tinkering with this.

**Comment by trevordmiller** [comment]
Moved to egghead-ui: https://github.com/eggheadio/egghead-ui/issues/107
