### ISSUE TITLE
Self-approval milestone improvements

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#190]
We could show instructors their progress towards self-approval (perhaps reusing how we do this with the `Get Published` milestone.

We could show/filter instructors that can self-approve in the `LessonGroups` `In Review` tab so mentors can wait to review to give instructors a chance to review and approve on their own.

We could improve the lesson actions for instructors who have passed this milestone. Perhaps the "Propose" option could become a direct "Upload Lesson" etc.

We could make the self-approval unlocking occur on 12+ approved lessons instead of published, so that if they have a course/lessons in the queue that would bump them past the 12+ count, they don't have to wait.

We could email instructors with an explanation of self-approval when instructors unlock self-approval.

**Comment by johnlindquist** [comment]
It would be cool to display the badges for each of their published courses on the instructor page. A nice reminder of their awesomeness.

^Building on that, a "Click badge to tweet about course" or some other form of helping them self-promote.

**Comment by trevordmiller** [comment]
@johnlindquist 
> "It would be cool to display the badges for each of their published courses on the instructor page. A nice reminder of their awesomeness."

Agreed. The great @vojtaholik has your back; this  has been designed and is waiting to be implemented: https://github.com/eggheadio/egghead-instructor-center/issues/157

![image](https://cloud.githubusercontent.com/assets/5497885/24224088/e72b2476-0f1e-11e7-9ba4-64e7d14d5c51.png)

> "^Building on that, a "Click badge to tweet about course" or some other form of helping them self-promote."

Good idea. I added it to the paper doc for Vojta.
