### ISSUE TITLE
Polish title card component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#199]
Title cards have been updated to place the title + [description] inside the title card component with updated text styles and a lighter background color:

![image](https://cloud.githubusercontent.com/assets/5497885/24315566/50db8048-10ad-11e7-80b3-77fecc03561b.png)

![image](https://cloud.githubusercontent.com/assets/5497885/24315559/489bfa20-10ad-11e7-9561-ee6f98a59281.png)

**Comment by vojtaholik** [comment]
_update_
CTAs added
![image](https://cloud.githubusercontent.com/assets/25487857/24360152/c9d5fe78-1306-11e7-89e0-6d9f49ccc31d.png)

**Comment by trevordmiller** [comment]
Thanks @vojtaholik - moving the CTA bits to https://github.com/eggheadio/egghead-instructor-center/issues/176; this issue is just for the updated  title + description styles (currently the `TitleCard` component which is only in the instructor center and wraps the egghead-ui `Card` component).

Currently looks like this:
![image](https://cloud.githubusercontent.com/assets/5497885/24371075/eff3fae4-12e6-11e7-9a88-a4e8d44297da.png)

But will be updated to match this issue ^
