### ISSUE TITLE
Improve usefulness of "Instructors" screen

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#200]
Break up tabs into more useful sections by priority of follow up; "Mentees" (your own instructors you are mentoring if it exists), "New", etc.

Would be good to filter on endpoint to speed up requests

**Comment by joelhooks** [comment]
I want to evolve the lesson queue and the instructor listing to provide a more unified "dashboard" for content publication. This will shift the focus from content items to the humans that are creating the content in some ways. 

We will likely integrate with a proper CRM (close.io, salesforce) to help facilitate this. 

This will probably result in a migration away from tabs in favor of exposing information in a "heads up" format that allows drilling in to details. 

This is just a heads up about the high level direction of these screens.

**Comment by trevordmiller** [comment]
Ok, I would like to discuss these things with you before pulling triggers if that's ok.

**Comment by joelhooks** [comment]
There will be significant amounts of discussion and planning about this, similar to the response here: https://github.com/eggheadio/egghead-instructor-center/issues/201#issuecomment-289165779

**Comment by trevordmiller** [comment]
Sounds good. I'd like to keep this issue open as a minimal next step to improve the instructors screen in a small way in the short term. I feel breaking up the "Published" and "Unpublished" tabs into smaller more actionable tabs with the endpoint data abailable would be a useful iteration for now.

**Comment by trevordmiller** [comment]
Closing this issue for now, can open a new one if needed later
