### ISSUE TITLE
Finish final pieces needed to retire instructor/mentor sections of egghead.io

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#201]
- Code example submission (plunkr or github repo)
- Lesson editing
- Course viewing/creation/editing
- Instructor invite
- Instructor profile editing

**Comment by joelhooks** [comment]
Lesson editing/creation, course creation/editing, instructor invites, and profile editing are likely to remain where they are at URL wise. Meaning they will end up on egghead.io at their existing routes. 

All of these need design discussion. 

Is "code example" simply the field when editing a lesson related to supplying a code example?

**Comment by trevordmiller** [comment]
> "Lesson editing/creation, course creation/editing, instructor invites, and profile editing are likely to remain where they are at URL wise. Meaning they will end up on egghead.io at their existing routes."

But I will still be able to re-build them in this repo, even if we export and render them in egghead-rails - right?

> "All of these need design discussion."

Yes, I understand. This is just a placeholder for me to keep track and discuss what is missing to make the experience "complete" in a backwards compatible sense.

> "Is "code example" simply the field when editing a lesson related to supplying a code example?"

Yes.

**Comment by joelhooks** [comment]
It depends, it's quite a lot of work so where it lands is more of a circumstance of when it is worked on and by whom.

If these types of placeholder issues are useful to you that is totally fine.

I'd prefer to capture and organize  mid-to-long term product level items in Paper so we can provide background and supporting information as we collaboratively design solutions. This gives us looser coupling to the actual implementation projects and builds a reference-able catalog of information. 

https://paper.dropbox.com/folder/show/Design-Research-Notes-e.iX7ZavGxujPFwhjOZcQs9pudWiBenSjThoWVoeBYrAq1yTkGpi

The course CRUD is of "project" size. 

Instructor inviting and profile editing is very low priority.

**Comment by trevordmiller** [comment]
Ok sounds good. Will close this and move to paper.
