### ISSUE TITLE
"Request Changes" notes

### ISSUE THREAD

**Issue by zacjones93** [eggheadio/egghead-instructor-center#202]
As a mentor, I would like to display a message when requesting changes on a lesson so that the instructor knows exactly why the lesson was rejected

The current workflow for requesting changes for a lesson is to hit the `request changes` button in IC and explaining what need work in Slack.

This could all take place in the IC.

**Comment by trevordmiller** [comment]
Hey @zacjones93, I'd love to see this as well. With the change in approach to keep lessons in egghead-rails, I opened this up on that board and am going to close this duplicate.

https://github.com/eggheadio/egghead-rails/issues/1315
