### ISSUE TITLE
Remove individual lesson screen and link to egghead.io lesson screen instead

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#203]
We plan to have lesson and course viewing only exist on egghead.io, with relevant instructor / mentor actions available if the current user has that data in their hypermedia API responses. With that in mind, the individual lessons (instructor.egghead.io/lessons/{lessonSlug}) should be removed from the Instructor Center, and any links to it should be replaced with links to egghead.io/lessons/{lessonSlug}.

**Comment by joelhooks** [comment]
This is a future task. The existing lesson page doesn't accommodate the state transition functionality, and the update is still in design phase.

**Comment by trevordmiller** [comment]
Ok just completed this but will revert. Closing this for now, let me know when it is needed and I'll redo.
