### ISSUE TITLE
Polish revenue card component

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#209]
![image](https://cloud.githubusercontent.com/assets/5497885/24722051/781f82d4-19ff-11e7-9653-03a74d9e1cf7.png)

- Remove the details button.
- Update text styles to match mock.
- Add data points to the initial view to match the mock.
- Add a toggle between revenue and minutes watched to match mock
- Simplify the labels to match mock.

**Comment by trevordmiller** [comment]
@joelhooks @vojtaholik This seems like it is ready to be implemented to me. Is there anything you would like to discuss before I start this next iteration?

**Comment by trevordmiller** [comment]
The flipping transition animation could be abstracted in the `ToggleOpen` component so it is applied by default to any "flipping" situations using `ToggleOpen` (currently the revenue card and lesson proposing in the requested lessons card). Might also be good to rename `ToggleOpen` to `Step`.

**Comment by joelhooks** [comment]
"flipping" doesn't need to be literal, and should have some general design consideration.

**Comment by trevordmiller** [comment]
Understood, I was just using that term to mean toggling to a more detailed state

**Comment by trevordmiller** [comment]
For this first iteration, I would suggest just keeping it simple with a CSS transition; probably opacity fade out first view, fade in next view.

**Comment by joelhooks** [comment]
Not keen on a crossfade here.

I'd like to have Vojta update the design with a transition  in mind, this doesn't need to occur today. It might not be worth the effort if this will just transition to a stats page anyway.

If you want to take the other items and add quick fixes, that's fine. Just skip the transition.

**Comment by trevordmiller** [comment]
Ok. I would suggest that whatever is used for the flip/switching between views isn't specific to revenue, that way we can apply it to the `ToggleOpen` component and it could be used wherever there is a flip/switch - currently this occurs with 1) the revenue card and 2) the "promote" toggle on the requested lessons card:
![inline-view-flipping](https://cloud.githubusercontent.com/assets/5497885/24572224/2f7e67ee-1634-11e7-86b6-be47cbe0c8e6.gif)

**Comment by vojtaholik** [comment]
@trevordmiller I'd say that toggle on the requested lessons card is a CTA button and that's different from view switch. So not sure about using same toggle/switch element for both cases. When you propose a new topic (that button is a switch), you should be able to get back to a previous list too – cancel/back button would do it. I imagine it as a next page with different content while revenue card has just another "composition". Also keeping in mind that we might have more "steps" within one card in the future.

I'll update revenue card design with transition in mind. 
Good work! 👍

**Comment by trevordmiller** [comment]
@vojtaholik What I mean by reusing is that I am using the logic in a shared component, but the UI can be different; so the actual flipping/switch between 1 or more steps can be attached to any click handler (a button, a chart, whatever) :)

**Comment by vojtaholik** [comment]
@trevordmiller Oh sorry, that makes sense! :)

I took it from other end and this is what I came up with. I've just added a switch between revenue/minutes, think we don't need to show both charts in extended view. What do you think? 

![image](https://cloud.githubusercontent.com/assets/25487857/24666717/6eebaf10-1961-11e7-8ea7-55071e516059.png)



Of course we could get more fancy with a switch but I'd rather focus on future version with more options.

 I'd animate a chart when switched - simple repositioning based on it's value. Similar to on-load grow.

**Comment by joelhooks** [comment]
this looks good to me @vojtaholik

**Comment by trevordmiller** [comment]
Sounds good. Moving this issue to "Ready to implement".

**Comment by trevordmiller** [comment]
Closed by https://github.com/eggheadio/egghead-instructor-center/pull/215
