### ISSUE TITLE
Estimated release dates

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#219]
The thing I get asked the most out of anything else is "when is my course going to be released"? Would be good to build into the Instructor Center some sort of visible queue with estimates and how the process works; could combine it with stand-alone lesson release estimates as well.

> "will there ever be any structure around release dates for courses? Currently They all just sit in the queue and as the creators we have no real insight into when it will be released?
^ not that I'm concerned about *how soon*  something will go live, I'm just curious if this is something that will be improved?"

**Comment by joelhooks** [comment]
We don't want to provide this right now.

https://eggheadio.slack.com/archives/C034KASSG/p1491851508559280

This is about as specific as we're willing to get: https://eggheadio.slack.com/archives/G4E8YCVNF/p1491168159906071

**Comment by trevordmiller** [comment]
I do understand the concern that we don't want to tie ourselves to a specific schedule. However, this is the most frequent question I am asked and is a common source of frustration for instructors who have worked hard on their courses; for example, I've had six instructors reach out to me in private messages in the last two weeks asking about their course releases, even after I gave most of them the suggested answer. I feel something like this mock below would solve the problem, while not adding any issues or extra work on our end other than updating the sort order every week or so:
![image](https://cloud.githubusercontent.com/assets/5497885/24891819/8a1e0778-1e35-11e7-9922-040f2a25923a.png)

@joelhooks What do you think of this mock? I know we have some of it in place currently on egghead.io instructor login homepage and https://egghead.io/courses/sort, but tying it together with the descriptions in the mock I think would help.

**Comment by joelhooks** [comment]
Definitely not in favor of giant blocks of text inline. We are dealing with well above average intelligence users that can grasp complex emerging processes. No need for a constant reminder. 

Another option is to write an article describing the process as it is now in an article and create a discrete link to it published inside of the instructor guide. 

This will give us a direct link to the FAQ. 

We can also include a summary and a link in our instructor onboarding emails. 

If that sounds OK, you could make an outline or first draft in Paper for collaboration, and I will get it published ASAP

**Comment by trevordmiller** [comment]
Sounds good, I'll make a first draft in Paper

**Comment by trevordmiller** [comment]
Moved to instructor 101 guide: https://github.com/eggheadio/egghead-instructor-101-guide/issues/25
