### ISSUE TITLE
Polish LessonActions

### ISSUE THREAD

**Issue by trevordmiller** [eggheadio/egghead-instructor-center#220]
# Changes

The `LessonActions` component needs a few style tweaks:
- Each possible lesson action needs a custom icon; here is what is being used so far:
https://github.com/eggheadio/egghead-instructor-center/blob/master/src/utils/lessonStates/index.js#L6-L84
- A max width should be added to the lesson actions on desktop to better match the mocks
- A left border should be added on the first lesson action on desktop to better match the mocks
- Don't display Replace and Upload on phone/tablet

# Mocks

https://app.zeplin.io/project.html#pid=58caceae349a0d1341e322a5&sid=58db9d6f43c40c913fc802fa

# Note

Ensure it works well in `LessonOverview` and `LessonDetails` components where it is currently being used.

**Comment by trevordmiller** [comment]
@vojtaholik @joelhooks I made this story from the Slack discussion; it is in the "Discussion" column on the board. Does this sound ready to go or do we need to discuss or design anything else?

**Comment by vojtaholik** [comment]
@trevordmiller @joelhooks sounds good, I think you've covered everything

request svg icon -> http://cloud.egghead.io/0M1T0Q2i0m0L
zeplin updated

list with actions https://zpl.io/Z1cQKkD 
page https://zpl.io/g2xGs

**Comment by vojtaholik** [comment]
![image](https://cloud.githubusercontent.com/assets/25487857/24881339/c8098906-1e3d-11e7-89ea-668b54b65993.png)
mobile

**Comment by trevordmiller** [comment]
Thanks @vojtaholik. How about when there is only one lesson action available, or none? Also, do you want other icons for the other possible states? Here is a list of the possible states with the `icon` of each being what is currently used; the check is overused currently IMO:
https://github.com/eggheadio/egghead-instructor-center/blob/master/src/utils/lessonStates/index.js#L6-L84

**Comment by vojtaholik** [comment]
http://cloud.egghead.io/38160S2N0A3S 

what about something like
if 1–2 actions -> display on side
if more actions -> stack underneath
would it be possible? just thinking out loud

**Comment by trevordmiller** [comment]
@vojtaholik Yes that is possible, but it depends on the min/max of the other elements and available space. What would be best is if you could tell me what the maximum width of this piece should be:
![image](https://cloud.githubusercontent.com/assets/5497885/24882046/f5feea04-1dfc-11e7-984d-ac5986eca16e.png)
Then I can have the other items automatically overflow underneath if they can't fit in the remaining horizontal space to the right ^

**Comment by vojtaholik** [comment]
> Here is a list of the possible states with the icon of each being what is currently used; the check is overused currently IMO.

I'm not sure about using icon for every state. There's plenty of them and some of them are quite hard to describe using little pictogram. I tried using different colors for each, but that looked awkward too. Can we just use text and revisit later? :)

**Comment by vojtaholik** [comment]
> maximum width

![image](https://cloud.githubusercontent.com/assets/25487857/24882235/a6c2f40a-1e40-11e7-9f63-d8302355bb88.png)
300px? something like that.

**Comment by trevordmiller** [comment]
Sounds good

**Comment by joelhooks** [comment]
Some of these, particularly "upload" and "replace", are totally inappropriate for mobile.

**Comment by trevordmiller** [comment]
Added to the story to hide upload and replace on mobile

**Comment by joelhooks** [comment]
We could also argue that the mobile site row items could simply be "click through" to more actions and not try so hard to pack a bunch of functionality into the list.

The upload/replace is also not viable on tablets as well, which is something to consider

**Comment by trevordmiller** [comment]
Moved to egghead-ui: https://github.com/eggheadio/egghead-ui/issues/109
