### ISSUE TITLE
Revenue chart vs Window resize 

### ISSUE THREAD

**Issue by vojtaholik** [eggheadio/egghead-instructor-center#221]
Revenue chart is being weird when resized.
See http://cloud.egghead.io/3g393Q3W1U3b
Chrome, osx

**Comment by joelhooks** [comment]
While this is fiddled with, I'd like to see this card line up with the bottom of the other card it shares a "row" with, if possible. OCD nitpick

**Comment by trevordmiller** [comment]
Yeah we can do that. I'd like to switch to CSS grid as it handles this perfectly; will be stacked columns on mobile and then can be a consistent grid system on larger screen sizes.

**Comment by trevordmiller** [comment]
Can also use flex stretch, but CSS grid was designed for this.

**Comment by trevordmiller** [comment]
Fixed in latest egghead-ui release

**Comment by trevordmiller** [comment]
As for the lining up the cards, this is more complicated unless I switch everything to CSS grid (since different screen sizes and wrapping create different heights), which we can do but I'd like to address this separately
